using System.Linq;
using Content.Shared.Preferences;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Player;
using Robust.Shared.Prototypes;

namespace Content.Client._ECHO.UserInterface.Lobby;

/// <summary>
/// Holds character data on the side of the setup GUI.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class FancyCharacterPickerButton : Control
{
    public Action<Button.ButtonEventArgs>? OnPressed;

    /// <summary>
    /// Invoked if we should delete the attached character
    /// </summary>
    public event Action? OnDeletePressed;

    public FancyCharacterPickerButton(
        IPrototypeManager prototypeManager,
        ISharedPlayerManager playerMan,
        ButtonGroup group,
        HumanoidCharacterProfile profile,
        bool isSelected)
    {
        RobustXamlLoader.Load(this);

        SelectButton.OnPressed += args => OnPressed?.Invoke(args);
        SelectButton.ToggleMode = true;
        SelectButton.Group = group;
        var description = profile.Name;

        View.LoadPreview(profile);

        var highPriorityJob = profile.JobPriorities.SingleOrDefault(p => p.Value == JobPriority.High).Key;
        if (highPriorityJob != default)
        {
            var jobName = prototypeManager.Index(highPriorityJob).LocalizedName;
            description = $"{description}\n{jobName}";
        }

        SelectButton.Pressed = isSelected;
        DeleteButton.Visible = !isSelected;

        DescriptionLabel.Text = description;

        ConfirmDeleteButton.OnPressed += _ =>
        {
            Parent?.RemoveChild(this);
            Parent?.RemoveChild(ConfirmDeleteButton);
            OnDeletePressed?.Invoke();
        };

        DeleteButton.OnPressed += _ =>
        {
            DeleteButton.Visible = false;
            ConfirmDeleteButton.Visible = true;
        };
    }
}
